from voicingtts_nanovllm.llm import VoicingTTS

try:
    from voicingtts_nanovllm._version import version as __version__
except Exception:
    # `_version.py` is generated by setuptools_scm during packaging.
    __version__ = "0.0.0"

__all__ = [
    "VoicingTTS",
    "__version__",
]
